In [1]:
import numpy as np

In [2]:
np.random.seed(17)
A=np.random.randint(0,10,size=(5,5))
print("Matrix A\n",A)

Matrix A
 [[1 6 6 9 0]
 [6 4 7 4 7]
 [1 1 9 8 2]
 [3 6 6 9 9]
 [1 5 1 0 5]]


In [14]:

U,Sigma,Vt=np.linalg.svd(A)

print("Matrix U\n",U)
print("Matrix sigma\n",Sigma)
print("Matrix v_transpose\n",Vt)


Matrix U
 [[-0.43538398  0.49632843 -0.58070328 -0.44660856 -0.16560004]
 [-0.4721125  -0.38812273  0.51419293 -0.5454511  -0.25408515]
 [-0.43510099  0.51476426  0.46255004  0.19367148  0.54244235]
 [-0.60244294 -0.26490568 -0.19859246  0.66192893 -0.29882872]
 [-0.18788347 -0.51755345 -0.38078581 -0.16542472  0.7242065 ]]
Matrix sigma
 [25.21604797  9.2542578   5.48110925  3.27423941  1.93557094]
Matrix v_transpose
 [[-0.22598197 -0.37634485 -0.54074855 -0.58334678 -0.41784475]
 [-0.28418424 -0.24172197  0.30115892  0.50230153 -0.71958758]
 [ 0.36314568 -0.74079562  0.49364836 -0.22924002  0.15201109]
 [-0.52081762 -0.46524829 -0.28972128  0.39870352  0.51902804]
 [-0.68194258  0.18628182  0.53783564 -0.44258809  0.12289018]]


In [16]:
Sigma_mat = np.diag(Sigma)
reconstructed_A = U.dot(Sigma_mat).dot(Vt)
is_equal = np.allclose(A, reconstructed_A, atol=tolerance)

if is_equal:
    print("A is equal to U Sigma V^T")
else:
    print("A is not equal to U Sigma V^T")

A is equal to U Sigma V^T


In [20]:
rank_A = np.linalg.matrix_rank(A)
print("Rank of matrix A:", rank_A)

Rank of matrix A: 5


In [21]:
#Rank 2 Approximation
rank_2_A = U[:, :2] @ np.diag(Sigma[:2]) @ Vt[:2, :]
print("\nRank-2 approximation of matrix A:")
print(rank_2_A)


Rank-2 approximation of matrix A:
[[1.17567885 3.02149792 7.31996482 8.71151482 1.28220231]
 [3.71100228 5.34852858 5.35581069 5.14047289 7.55896893]
 [1.12558162 2.97757221 7.3674868  8.79304975 1.15645186]
 [4.12962338 6.30972402 7.47634301 7.63036018 8.11164868]
 [2.43175112 2.94074599 1.1194702  0.35789962 5.42613142]]


In [22]:
#Rank 3 Approximation
rank_3_A = U[:, :3] @ np.diag(Sigma[:3]) @ Vt[:3, :]
print("\nRank-3 approximation of matrix A:")
print(rank_3_A)


Rank-3 approximation of matrix A:
[[0.01982316 5.37937489 5.74873239 9.44116246 0.79836652]
 [4.73447304 3.26070901 6.74708338 4.49439482 7.98738901]
 [2.04626024 1.09944248 8.61902721 8.21186043 1.54184363]
 [3.73433677 7.11608522 6.93900333 7.87988955 7.94618355]
 [1.67381937 4.48688174 0.08916257 0.83635304 5.10886474]]
